= General Apiman Manager Configuration

== Logging In

Once Apiman is running, you should be able to log in to the API Manager by pointing your browser at the following URL:

[source,log]
----
http://localhost:8080/apimanui/

or

https://localhost:8443/apimanui/
----

You may log in with credentials *admin/admin123!*

[CAUTION]
====
We strongly advise that you immediately change the Keycloak admin user's password, as well as the *_admin_* user found in the *_apiman_* realm!
====

== General Configuration

Apiman is made up of a number of different components, many of which can be configured to use various implementations and/or providers.

When downloading and installing Apiman, the default distribution includes reasonable default values for all options.

This section details these options and explains the default values.

=== Configuration Properties

All Apiman WARs share a common configuration file called *apiman.properties*, which can be found in:

* *standalone/configuration/apiman.properties* for WildFly.
* *conf/apiman.properties* for Tomcat.

This file therefore can contain configuration settings for all four applications: API Manager, API Manager UI, API Gateway, Developer Portal.
In many production-grade deployments, these will be split up into separate deployments (especially the gateways).

Please refer to the `apiman.properties` file itself, as well as this document, for more information on each property's purpose and possible values.

TIP: If you are running a non-Servlet gateway implementation (e.g. Vert.x), then you should refer to that gateway's configuration documentation to understand how to configure it.

=== API Manager Database

The API Manager, by default, is a typical CDI application and uses JPA/Hibernate to persist its data.
The JPA layer requires a data source to connect to a supported database.

Apiman's Manager JDBC datasource JNDI name is: `java:/apiman/datasources/apiman-manager`

As of Apiman 3, we use Liquibase to initialise the database and apply migrations. If you prefer to do this manually, set the system property `liquibase.should.run=false`.

To add or remove datasources, you can:

* Open `standalone/configuration/standalone-apiman.xml` and edit the `datasources` subsystem.
* Use the WildFly CLI.
* Use the WildFly Administration console.

Out of the box, this data source is usually a simple H2 configuration, but you can (of course) change it to support whatever database you desire.

To make getting started easy, we ship Apiman with H2, Postgres, and MySQL JDBC drivers; system properties and environment properties are available that synchronise settings across Apiman to make database configuration as seamless as possible.

https://github.com/apiman/apiman/issues/2265[Let us know] if you want Apiman to ship with drivers for other databases by default.

You are always able to edit `standalone-apiman.xml` and `apiman.properties` if you have an advanced setup that is not catered for by Apiman's default configuration.

[[required_parameters]]
==== Required Parameters

NOTE: This only applies to WildFly distribution, currently.If you are using Tomcat, you will need to configure the datasources manually.

.Required Params
[cols="2,1,4",options="header"]
|===

| Name
| Type
| Description

a| * System property: apiman.db.driver
  * Env var: APIMAN_DB_DRIVER
| String
a| WildFly database driver name, as defined in `datasources/drivers`

* *Default Value*: h2
* *Allowed Values*: postgresql9, mysql8, (plus any value you have manually configured)

a| * System property: apiman.db.url
* Env var: APIMAN_DB_URL
| String
a| Apiman database JDBC URL

* *Default Value*: h2 (local file database)

a| * System property: apiman.db.username
* Env var: APIMAN_DB_USERNAME
| String
a| Apiman database username

* *Default Value*: sa

a| * System property: apiman.db.password
* Env var: APIMAN_DB_PASSWORD
| String
a| Apiman database password

* *Default Value*: sa

a| * System property: liquibase.should.run
| Boolean
a| Whether https://www.liquibase.org/[Liquibase^], our SQL change management engine, should run at startup to initialise your database and/or apply the latest SQL migrations.

* *Default Value*: true

|===


.Examples
|===
|Setup | Command

|Postgres -- system properties
a|
[source,shell]
----
./bin/standalone.sh \
    -Dapiman.db.url="jdbc:postgresql://localhost:5432/apiman" \
    -Dapiman.db.username=postgres \
    -Dapiman.db.password="admin123\!" \
    -Dapiman.db.driver=postgres9
----

|Postgres -- env vars
a|
[source,shell]
----
export APIMAN_DB_URL="jdbc:postgresql://localhost:5432/apiman"
export APIMAN_DB_USERNAME="postgres"
export APIMAN_DB_PASSWORD="admin123\!"
export APIMAN_DB_DRIVER="postgresql9"

./bin/standalone.sh
----

|MySQL/MariaDB -- system properties
a|
[source,shell]
----
./bin/standalone.sh \
    -Dapiman.db.url="jdbc:mysql://localhost:3306/apiman" \
    -Dapiman.db.username=root \
    -Dapiman.db.password="admin123\!" \
    -Dapiman.db.driver=mysql8
----

|MySQL/MariaDB -- env vars
a|
[source,shell]
----
export APIMAN_DB_URL="jdbc:mysql://localhost:3306/apiman"
export APIMAN_DB_USERNAME="root"
export APIMAN_DB_PASSWORD="admin123\!"
export APIMAN_DB_DRIVER="mysql8"

./bin/standalone.sh
----

|===

==== Advanced configuration

You can set the Hibernate dialect manually yourself, including via a fully qualified class name (FQCN):

[source,properties]
----
apiman.hibernate.dialect=io.apiman.manager.api.jpa.ApimanMySQL8Dialect
----

Note that the following dialects are available:

* `ApimanH2Dialect` / `h2`
* `ApimanMySQL8Dialect` / `mysql8`
* `ApimanOracle19Dialect` / `oracle19`
* `ApimanPostgreSQLDialect` / `postgres9`

Additional DDLs for various databases can be found in `apiman/ddls/`.

If you have issues with DDLs, please open a https://github.com/apiman/apiman/issues[GitHub Issue^].

== Custom API Catalog

The API Manager has a feature allowing users can import APIs from a globally configured API Catalog.

By default, Apiman comes with a community catalog that contains a set of common public APIs such as Flickr and Netflix.

When deploying Apiman into an enterprise setting, it is often useful to replace the community API Catalog with something that lists out the internal APIs available within the enterprise.

You can also provide your own custom implementation which is able to integrate with your internal systems. For example, by connecting to your internal API registry.

=== High Level Overview

. Describe your enterprise APIs as Apiman API Catalog JSON
. Make your enterprise API Catalog available in URL form
. Point Apiman at your enterprise API Catalog

==== Create a Custom Enterprise API Catalog JSON

The first thing you will need to do is express all of your enterprise APIs as a
JSON file.
The format of the JSON file is specific to Apiman.
You can find an example of the format here:

https://github.com/apiman/apiman-api-catalog/blob/master/catalog.json

==== Make Your Enterprise API Catalog Available

Now that you have a custom JSON based API Catalog, you need to make it available
at a URL accessible to the API Manager.
This can either be done by stashing it in some web server location, so you have an HTTP-based URL, or you can store it locally on the API Manager server to have a valid file based URL.

==== Point Apiman at Your Enterprise API Catalog

The last step is to make Apiman aware of your custom API Catalog file.  The
catalog is configured in the `apiman.properties` file via these properties:

[source,properties,subs=attributes+]
----
apiman-manager.api-catalog.type=io.apiman.manager.api.core.catalog.JsonApiCatalog
apiman-manager.api-catalog.catalog-url=https://cdn.rawgit.com/apiman/apiman-api-catalog/{apiman-version-release}/catalog.json
----

Simply change the URL defined by the `apiman-manager.api-catalog.catalog-url` property and you're good to go!

[TIP]
====
For even more customization, you can implement your own API Catalog Java plugin.

This approach will allow you to find your APIs in whatever location they happen to be (e.g. a database, registry, etc).

Please see the Developer Guide for more information on how to create a truly custom API Catalog.
====

== Custom Plugin Registry

The API Manager uses a plugin registry to show admin users a list of available plugins that can be installed.
Apiman comes with an official plugin registry that shows a list of the standard Apiman plugins.
If your enterprise implements a large number of custom policies, you may find it useful to replace the standard registry with one that includes your custom plugins in the list.

=== High Level Overview

. Describe your enterprise plugins in a registry JSON file
. Make your enterprise plugin registry available in URL form
. Point Apiman at your enterprise plugin registry

==== Create a Custom Enterprise Plugin Registry JSON

The first thing you will need to do is express all of your enterprise plugins as a JSON file.
The format of the JSON file is specific to Apiman.
You can find an example of the format here:

https://github.com/apiman/apiman-plugin-registry/blob/master/registry.json

==== Make Your Enterprise Plugin Registry Available

Now that you have a custom JSON based plugin registry, you need to make it available at a URL accessible to the API Manager.
This can either be done by stashing it in some web server location so you have an http based URL, or you can store it locally on the API Manager server so as to have a valid file based URL.

==== Point Apiman at Your Enterprise Plugin Registry

The last step is to make Apiman aware of your custom plugin registry file.
The registry is configured in the *apiman.properties* file via the following property:

[source,properties,subs=attributes+]
----
apiman-manager.plugins.registries=https://cdn.rawgit.com/apiman/apiman-plugin-registry/{apiman-version-release}/registry.json
----

The value of this property is a comma-separated list of URLs.
Each URL in the list should point to a valid plugin registry JSON file.
To include your enterprise plugins in the list, simply add the URL to your plugin registry to the end of the existing list.

== Property Replacement in Policy Config

It is often useful to externalize certain information that varies from one deployment environment to another.

For example, you may have an LDAP server for authentication, but you have one in the Test deployment environment and a different one in Production.

Rather than configure your Apiman policies differently in each environment (to match the actual LDAP connection info) you can externalize those settings into system properties or environment variables.

Once that is done, you can refer to those properties/variables in your Apiman policy configuration.

=== High Level Overview

. Externalize values into system properties or environment variables
. Reference a system property or environment variable in a policy

=== Externalize Values

Depending on your deployment strategy, how you do this may vary.
If you are using WildFly, for example, you can set system properties in the `standalone.xml` file or by passing them in via -D parameters on startup.

For more information, see the https://docs.wildfly.org/23/Admin_Guide.html#General_configuration_concepts[WildFly Admin Guide].

Describing all approaches to setting system properties and environment variables
is out of scope for this document.

=== Reference a System Property or Environment Variable

Once you have some values externalized into system properties or environment
variables, you can reference them easily in your Apiman policies.

All you need to do is use the Ant-style syntax to refer to your externalized values, like this:

[source,text]
----
${MY_ENVIRONMENT_VARIABLE}
----

A variable of this style can be used in any Apiman policy configuration field.
The variables are resolved when the policy configuration is first loaded, and
then cached.
To change a value, you must restart your server.

TIP: When resolving variables, if there is an environment variable with the same
name as a system property, the value of the *system property* will be used.
