= Apiman Vert.x Gateway

The apiman Vert.x distro is our premiere gateway offering and should provide the best performance characteristics of any of our platforms.

The implementation is the _apiman gateway_ only, and hence is normally paired with the Manager and UI from the Servlet version (e.g. WildFly, EAP, Jetty, etc), but it can be run headless for specific workloads.

There are a few different common configuration examples shipped with the Vert.x distro and are outlined in more detail below, but you can customise your configurations however you see fit.

== Download & Installation

Download the apiman Vert.x distro from http://www.apiman.io/latest/download.html#vertx[apiman.io downloads] page.

Extract the archive and execute it with:

```
unzip apiman-distro-vertx-{{ book.apiman.version.release }}
cd apiman-distro-vertx-{{ book.apiman.version.release }}
./apiman-gateway.sh --conf configs/conf-es.json
```

Where `config-es.json` is your configuration file. Refer to the config and its annotations for additional detail.

If you have started successfully then see console output something like:

```
$ ./apiman-gateway.sh --conf configs/conf-es.json
[INFO ] ... InitVerticle - Starting verticle: INITIALISER. UUID: 7c577980-716c-4bb9-93a8-e517b0ae15a5.INITIALISER.
[INFO ] ... InitVerticle - Will deploy 1 of type API
[INFO ] ... InitVerticle - Will deploy 8 of type HTTP
[INFO ] ... ApiVerticle - Starting verticle: API. UUID: aad6996f-16e0-4a87-baa7-5fc4843c76bf.API.
[INFO ] ... HttpGatewayVerticle - Starting verticle: HTTP. UUID: effa81a3-fa74-4bd6-813f-8ad09c86344b.HTTP.
<snip>
[INFO ] ... HttpGatewayVerticle - Starting verticle: HTTP. UUID: 09827a46-6d41-4ab1-aef2-0d152e31fe15.HTTP.
[INFO ] ... InitVerticle - Will deploy 0 of type HTTPS
[WARN ] ... ApiVerticle - API is running in plaintext mode. Enable SSL in config for production deployments.
[INFO ] ... InitVerticle - Successfully deployed all verticles
[INFO ] ... InitVerticle - Gateway API port: 8081
[INFO ] ... VertxIsolatedDeployer - Succeeded in deploying verticle
```

== Test your installation

You can quickly verify whether your installation is working, you might try (if using default host, port and protocol, otherwise alter):

  $ curl -v 'http://apimanager:apiman123!@localhost:8081/system/status'

WARNING: You must alter the default passwords and enable SSL for production deployments, otherwise your system will be at risk

== Configurations

This gateway's counterpart to `apiman.properties` is a simple JSON-based configuration file, examples of which are provided in the `configs` directory.

=== Elasticsearch

The Elasticsearch config `conf-es.json` comes pre-configured with Elasticsearch components.

You should alter the `variables.apiman.es` configuration to match your Elasticsearch setup.

You can either use the Elasticsearch instance bundled with the _apiman Manager_, or run your own cluster (which is the preferred option for production).

TIP: You can optionally also set the username and password - this is only useful if you are using something like Elasticsearch Shield to enable basic authentication.

```json
"variables": {
  "apiman": {
    "es": {
      "protocol": "http",
      "host": "localhost",
      "port": 19200, // <1>
      "username": null,
      "password": null,
      "timeout": 10000
    }
  }
}
```
<1> The default port of a standalone ES cluster is typically 9200. The ES bundled with the _apiman Manager_ is set to 19200 by default to avoid port clashes.

=== Headless Elasticsearch

The apiman headless Elasticsearch config `conf-headless-es.json` uses an immutable registry to load its configuration from a local or remote JSON file. All other components (e.g. metrics, rate-limiting, etc) use Elasticsearch.

First, alter your configuration as detailed in the <<Elasticsearch>> section.

Then, modify the `registry.config` section of the config:

```json
"registry": {
  "class": "io.apiman.gateway.engine.vertx.polling.URILoadingRegistry",
  "config": {
    "configUri": "file:///path/to/my/json/reg-config.json", // <1>
    "auth": "NONE" // <2>
  }
},
```
<1> A file, http or https URI to a JSON file containing the registry configuration, as detailed in <<File Format>>.
<2> Authentication method to retrieve the file, as detailed in <<Authentication Methods>>.

For full documentation on this registry, refer to TODO. 

==== Authentication Methods

For http and https, 4 `auth` methods are supported:

.*BASIC*

Standard BASIC auth with static credentials.

```json
"config": {
  "configUri": "https://example.org/reg-config.json", // <1>
  "auth": "BASIC", // <2>
  "username": "${USERNAME}", // <3>
  "password": "${PASSWORD}" // <4>
}
```
<1> Location of config.
<2> BASIC auth methods
<3> Username. In this example as a variable that can be defined in the environment, properties or `variables` section.
<4> Password. In this example as a variable that can be defined in the environment, properties or `variables` section.

.*Keycloak OAuth2*

A convenience Keycloak OAuth2 implementation, allowing you to paste your client configuration from the Keycloak console into the `config` section.

. Log into Keycloak (e.g. http://localhost:8080/auth)
. `Clients` -> `Your-Client` -> `Installation`
. Select `Keycloak OIDC JSON` for `Format Option`
. Copy the contents and merge into the `config` selection where indicated below.

The precise configuration you need to provide will vary depending upon your Keycloak setup, but should be broadly similar.

```json
"config": {
  "auth": "KeycloakOAuth2",
  "flowType": "password", // <1>
  "username": "foo", // <2>
  "password": "bar", // <3>
  // Start paste & merge of your Keycloak config here.
  // This is an example...
  "realm": "apiman",
  "realm-public-key": "< snip >",
  "auth-server-url": "http://localhost:8080/auth",
  "ssl-required": "none",
  "resource": "apiman-gateway-api",
  "credentials": { // <4>
    "secret": "217b725d-7790-47a7-a3fc-5cf31f92a8db"
  }
  // End paste here.
}
```
<1> Carefully set the correct OAuth2 flow for your configuration. OAuth2 flow type: `flowType = AUTH_CODE | AUTH_JWT | CLIENT | PASSWORD`
<2> `username` if using password `flowtype`. Other flow types don't use this field.
<3> `password` if using password `flowType`. Other flow types don't use this field.
<4> You may find that due to a limitation of the underlying OAuth2 library you are required to provide a `credentials` section to avoid errors. In this case you can change your client type to `confidential`, or simply provide a dummy `credentials` section.

==== File Format

Configuration is provided via JSON file, rather than the apiman manager. It consists of:

* An `api` array containing your APIs.
* A `clients` array containing your Clients.

```json
{
    "apis": [{
        "publicAPI": true, // <1>
        "organizationId": "foo", // <2>
        "apiId": "foo", // <3>
        "version": "foo", // <4>
        "endpoint": "http://www.example.org/my-api-uri/", // <5>
        "endpointType": "rest", // <6>
        "endpointContentType": "json", // <7>
        "endpointProperties": {}, // <8>
        "parsePayload": false, // <9>
        "apiPolicies": [{ // <10>
            // Plugin's JSON config.
           "policyJsonConfig": "{ \"responseCode\" : \"403\", \"ipList\" : [ \"1.2.3.4\" ] }", // <11>
           // Plugin coordinates.
           "policyImpl": "plugin:io.apiman.plugins:apiman-plugins-url-whitelist-policy:{{ book.apiman.version.release }}:war/io.apiman.gateway.engine.policies.IPWhitelistPolicy" // <12>
       }]
    }],
    "clients": [{
        "organizationId": "foo", // <2>
        "clientId": "fooClient", // <13>
        "version": "foo", // <4>
        "apiKey": "12345", // <14>
        "contracts": [{ // <15>
            "apiOrgId": "foo", // <16>
            "apiId": "foo", // <17>
            "apiVersion": "foo", // <18>
            "plan": "foo", // <19>
            "policies": [] // <11>
        }]
    }]
}
```
<1> Whether the API is public, and thus can be accessed directly without needing an API key.
<2> Organization this entity resides within.
<3> API's unique ID.
<4> API's version.
<5> API's backend (i.e. the API you are managing).
<6> Endpoint type. Can be `rest` or `soap`.
<7> Endpoint's preferred content type. Can be `json` or `xml`. This will ensure error messages, etc are returned in that format.
<8> Endpoint properties. See below for valid entries.
<9> Whether the payload should be parsed up-front (i.e. you are using a policy that doesn't work with body streaming). Avoid this unless it's an absolute necessity.
<10> API's policies: Applied in the order specified.
<11> The policy's configuration as JSON. Refer to the policy's documentation <link> to see the available options.
<12> Reference to the plugin the gateway by GAV. Please refer to the policy's documentation <link> to see the available options.
<13> Client's unique ID.
<14> Client's unique API key.
<15> Array of Contracts subscribing a Client to an API.
<16> The Organization of the subscribed API.
<17> The unique ID of the subscribed API.
<18> The version of the subscribed API.
<19> The plan name of the subscribed API.


.*Endpoint Properties:*
* Authorization type:
** Basic Auth: `"authorization.type": "basic"`
** Username: `"basic-auth.username": "<username>"`
** Password: `"basic-auth.password": "<password>"`
** SSL Required?: `"basic-auth.requireSSL": "<true|false>"`
* MTLS/MSSL: `"authorization.type": "<mtls|ssl>"`. You should also provide the corresponding SSL certificate settings in the gateway's config file.


.*Endpoint Type:*
* `rest`: Standard RESTful endpoint type.
* `soap`: SOAP endpoint type.


.*Endpoint Content Type:*
The `endpointContentType` indicates which format you want apiman's responses to be in (e.g. error messages): `"endpointContentType": "<json|xml>"`.
