= Wildfly & EAP

== Overview

This chapter explores downloading and installing the Apiman quickstarts which consists of both the _Apiman Manager and UI_ and _Apiman Gateway_.

== Installing in WildFly

Apiman can target WildFly as a runtime environment.
In order to install Apiman you will need to download both WildFly and the Apiman overlay distribution.
Once both are downloaded, it's a simple matter of unpacking both into the same location.

=== Download

First you will need to download both WildFly and Apiman:

* http://download.jboss.org/wildfly/{wildfly-version}/wildfly-{wildfly-version}.zip[Download WildFly]
* http://downloads.jboss.org/apiman/{apiman-version-release}/apiman-distro-wildfly-{apiman-version-release}-overlay.zip[Download Apiman {apiman-version-release}]

[source,bash,subs=attributes+]
----
wget https://download.jboss.org/wildfly/{wildfly-version}/wildfly-{wildfly-version}.zip

wget https://github.com/apiman/apiman/releases/download/{apiman-version-release}/apiman-distro-wildfly-{apiman-version-release}-overlay.zip
----


=== Unpack

Once both files have been downloaded, simply unpack both in the same location.

[source,bash,subs=attributes+]
----
unzip wildfly-{wildfly-version}.zip

unzip -o apiman-distro-wildfly-{apiman-version-release}-overlay.zip -d wildfly-{wildfly-version}
----

=== Run WildFly

The Apiman overlay contains everything needed to run Apiman, including:

* Apiman binaries (several WAR files)
* Apiman-specific WildFly configuration (*standalone-apiman.xml*)
* Apiman RDBMS datasource (h2)
* pre-configured *admin* user with password *admin123!*
* pre-configured h2 database (populated with default values)

For this reason, there is no additional configuration required to run Apiman.
Simply start up WildFly using the Apiman configuration file:

[source,bash,subs=attributes+]
----
cd wildfly-{wildfly-version}
./bin/standalone.sh -c standalone-apiman.xml
----

== Installing using Docker

Another option when installing Apiman is to use our docker image.
You're probably pretty familiar with docker if you're going that route, but here is an example of how to start up the Apiman docker image:

[source,bash,subs=attributes+]
----
docker pull apiman/on-wildfly:{apiman-version-release}
docker run -it -p 8080:8080 -p 8443:8443 apiman/on-wildfly:{apiman-version-release}
----

NOTE: You can find Apiman on https://registry.hub.docker.com/repos/apiman/[Docker Hub].

== Logging In

Once Apiman is running, you should be able to log in to the API Manager by pointing your browser at the following URL:

[source,bash]
----
http://localhost:8080/apimanui/
----

You may log in with credentials *admin/admin123!*

[CAUTION]
====
We strongly advise that you immediately change the Keycloak admin user's password, as well as the *_admin_* user found in the *_apiman_* realm!

You can do that by navigating to http://localhost:8080/auth/admin/.
====
