= JDBC Registry & Components
Marc Savy <marc@rhymewithgravy.com>
:toc:

NOTE: These components are presently optimised for Servlet editions of the gateway, whilst they will work with Vert.x the experience will likely be less performant than normal.

TIP: We ship a range of sample DDLs to get you started for all major databases. In your distribution look in `apiman/ddls` directory, or refer to the link:https://github.com/apiman/apiman/tree/master/distro/data/src/main/resources/ddls[Apiman Repo].

== Registry

To set your registry, assign your chosen implementation to:

```properties
apiman-gateway.registry=<IMPLEMENTATION>
```

.Available implementations:
[cols="2", options="header"]
|===

| Implementation
| Notes

| `io.apiman.gateway.engine.jdbc.PollCachingJdbcRegistry`
| *Recommended*. Works well in multi-node setups.

| `io.apiman.gateway.engine.jdbc.CachingJdbcRegistry`
| Works only in single node setups.

| `io.apiman.gateway.engine.jdbc.JdbcRegistry`
| Only recommended for very low volume or test setups; causes database calls to be issued on every request.

|===

=== Required Parameters

[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| datasource.jndi-location
| String
a| The JNDI location of the datasource you wish to use.

|===

Example:

```properties
apiman-gateway.registry=io.apiman.gateway.engine.jdbc.JdbcRegistry
apiman-gateway.registry.datasource.jndi-location=java:jboss/datasources/apiman-gateway
```

=== Optional Parameters

[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| cache-polling-interval
| Integer
a| Polling interval in millis

| cache-polling-startup-delay
| Integer
a| How long to wait before starting polling in millis

|===

== Metrics

Set the metrics implementation as shown:

```properties
apiman-gateway.metrics=io.apiman.gateway.engine.jdbc.JdbcMetrics
apiman-gateway.metrics.queue.size=10000 // Example.
```

=== Required Parameters

See <<Registry,Registry Required Parameters>>.

IMPORTANT: Must be configured with the JNDI location of the datasource to use.

=== Optional Parameters

[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| queue.size
| Integer
| Metrics maximum queue size

|===
