= Headless Registry
Marc Savy <marc@rhymewithgravy.com>

The apiman headless registry uses an immutable registry to load its configuration from a local or remote JSON file.

TIP: This registry is optimised for the Vert.x gateway implementation. Although it should work for other platforms, it is unlikely to be as performant.

== Example

```json
"registry": {
  "class": "io.apiman.gateway.engine.vertx.polling.URILoadingRegistry",
  "config": {
    "configUri": "file:///path/to/my/json/reg-config.json", // <1>
    "auth": "NONE" // <2>
  }
},
```
<1> A file, http or https URI to a JSON file containing the registry configuration, as detailed in <<File Format>>.
<2> Authentication method to retrieve the file, as detailed in <<Authentication>>.

== Required Parameters

[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| configUri
| String
a| URI to file containing registry configuration. Supports `file`, `http`, `https`.

| auth
| Enum
a| Auth mechanism to access resource indicated in `configUri`.

.*Must be one of:*
* NONE: No auth needed.
* <<BASIC>>: BASIC auth.
* <<Keycloak OAuth2,KEYCLOAKOAUTH2>>: Convenience Keycloak OAuth2 implementation.
* <<OAuth2,OAUTH2>>: Generic OAuth2.

Refer to the subsections for each auth mechanism for respective configuration options.

*Default value:* NONE.

|===

== Authentication

=== BASIC

Standard BASIC auth with static credentials.

.Required Parameters
[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| username
| String
a| A username. Consider using variable substitution.

| password
| String
a| A password. Consider using variable substitution.

|===

.Example
```json
"config": {
  "configUri": "https://example.org/reg-config.json",
  "auth": "BASIC",
  "username": "MyUsername",
  "password": "${PASSWORD}" // <1>
}
```
<1> The password in this example is defined as a variable to be substituted from the config variables, system properties or environment.

=== Keycloak OAuth2

A convenience Keycloak OAuth2 implementation, allowing you to paste your chosen client configuration from the Keycloak console into the `config` section.

To retrieve it:

. Log into Keycloak (e.g. http://localhost:8080/auth).
. `Clients` -> `<Your-Client>` -> `Installation`.
. Select `Keycloak OIDC JSON` for `Format Option`.
. Copy the contents and merge into the `config` selection where indicated below.

The precise configuration you need to provide will vary depending upon your Keycloak setup.

IMPORTANT: Due to a current limitation in the underlying OAuth2 library you may be required to provide a `credentials` section to avoid issues. You can change your client type to `confidential`, or simply provide a dummy `credentials` section.

.Example
```json
"config": {
  "auth": "KeycloakOAuth2",
  "flowType": "password",
  "username": "foo",
  "password": "bar",
  // Start paste & replace your Keycloak config here.
  "realm": "apiman",
  "realm-public-key": "< snip >",
  "auth-server-url": "http://localhost:8080/auth",
  "ssl-required": "none",
  "resource": "apiman-gateway-api",
  "credentials": {
    "secret": "217b725d-7790-47a7-a3fc-5cf31f92a8db"
  }
  // End paste here.
}
```

.Required Parameters
[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| flowType
| Enum
a| The OAuth2 flow for your configuration.

.Must be one of:
* PASSWORD
* CLIENT
* AUTH_CODE
* AUTH_JWT

|===

.Optional Parameters
[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| username
| String
a| A username. Usually only useful if using the password `flowType`.

| password
| String
a| A passwor. Usually only useful if using the password `flowType`.

|===

== OAuth2

TIP: The combination of required parameters and optional parameters will vary considerably depending upon your configuration.

.Required Parameters
[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| flowType
| Enum
a| The OAuth2 flow for your configuration.

.Must be one of:
* PASSWORD
* CLIENT
* AUTH_CODE
* AUTH_JWT

| oauthUri
| String
a| The OAuth2 URI.

| clientId
| String
a| The OAuth2 client ID.

| clientSecret
| String
a| The OAuth2 client secret.

|===

.Optional Parameters
[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| site
| String
a| Site URI

| publicKey
| String
a| Public key

| clientSecret
| String
a| Client secret

| username
| String
a| A username. Usually only useful if using the password `flowType`.

| password
| String
a| A password. Usually only useful if using the password `flowType`.

| authorizationPath
| String
a| The authorization path

| tokenPath
| String
a| The token path

| recovationPath
| String
a| The revocation path

| scopeSeparator
| String
a| The introspection path

| logoutPath
| String
a| The logout path (OIDC)

| useBasicAuthorizationHeader
| boolean
a| Whether to use BASIC auth header (OIDC)

| clientSecretParameterName
| String
a| Client secret query parameter name (OIDC)

| userInfoPath
| String
a| User info path (OIDC)

| introspectionPath
| String
a| User info path (RFC7662)

| userAgent
| String
a| User agent

| privateKey
| String
a| Private key

|===

== File Format

Configuration is provided via JSON file, rather than the apiman manager. It consists of:

* An `api` array containing your APIs.
* A `clients` array containing your Clients.

```json
{
    "apis": [{
        "publicAPI": true, // <1>
        "organizationId": "foo", // <2>
        "apiId": "foo", // <3>
        "version": "foo", // <4>
        "endpoint": "http://www.example.org/my-api-uri/", // <5>
        "endpointType": "rest", // <6>
        "endpointContentType": "json", // <7>
        "endpointProperties": {}, // <8>
        "parsePayload": false, // <9>
        "apiPolicies": [{ // <10>
            // Plugin's JSON config.
           "policyJsonConfig": "{ \"responseCode\" : \"403\", \"ipList\" : [ \"1.2.3.4\" ] }", // <11>
           // Plugin coordinates.
           "policyImpl": "plugin:io.apiman.plugins:apiman-plugins-url-whitelist-policy:{{ book.apiman.version.release }}:war/io.apiman.gateway.engine.policies.IPWhitelistPolicy" // <12>
       }]
    }],
    "clients": [{
        "organizationId": "foo", // <2>
        "clientId": "fooClient", // <13>
        "version": "foo", // <4>
        "apiKey": "12345", // <14>
        "contracts": [{ // <15>
            "apiOrgId": "foo", // <16>
            "apiId": "foo", // <17>
            "apiVersion": "foo", // <18>
            "plan": "foo", // <19>
            "policies": [] // <11>
        }]
    }]
}
```
<1> Whether the API is public, and thus can be accessed directly without needing an API key.
<2> Organization this entity resides within.
<3> API's unique ID.
<4> API's version.
<5> API's backend (i.e. the API you are managing).
<6> Endpoint type. Can be `rest` or `soap`.
<7> Endpoint's preferred content type. Can be `json` or `xml`. This will ensure error messages, etc are returned in that format.
<8> Endpoint properties. See below for valid entries.
<9> Whether the payload should be parsed up-front (i.e. you are using a policy that doesn't work with body streaming). Avoid this unless it's an absolute necessity.
<10> API's policies: Applied in the order specified.
<11> The policy's configuration as JSON. Refer to the policy's documentation <link> to see the available options.
<12> Reference to the plugin the gateway by GAV. Please refer to the policy's documentation <link> to see the available options.
<13> Client's unique ID.
<14> Client's unique API key.
<15> Array of Contracts subscribing a Client to an API.
<16> The Organization of the subscribed API.
<17> The unique ID of the subscribed API.
<18> The version of the subscribed API.
<19> The plan name of the subscribed API.


.*Endpoint Properties:*
* Authorization type:
** Basic Auth: `"authorization.type": "basic"`
** Username: `"basic-auth.username": "<username>"`
** Password: `"basic-auth.password": "<password>"`
** SSL Required?: `"basic-auth.requireSSL": "<true|false>"`
* MTLS/MSSL: `"authorization.type": "<mtls|ssl>"`. You should also provide the corresponding SSL certificate settings in the gateway's config file.


.*Endpoint Type:*
* `rest`: Standard RESTful endpoint type.
* `soap`: SOAP endpoint type.


.*Endpoint Content Type:*
The `endpointContentType` indicates which format you want apiman's responses to be in (e.g. error messages): `"endpointContentType": "<json|xml>"`.
