= Headless Registry
Marc Savy <marc@rhymewithgravy.com>
:toc:

The apiman headless registry uses an immutable registry to load its configuration from a local or remote JSON file.

TIP: This registry is optimised for the Vert.x gateway implementation. Although it should work for other platforms, it is unlikely to be as performant.

== Example

```json
"registry": {
  "class": "io.apiman.gateway.engine.vertx.polling.URILoadingRegistry",
  "config": {
    "configUri": "file:///path/to/my/json/reg-config.json", // <1>
    "auth": "NONE" // <2>
  }
},
```
<1> A file, http or https URI to a JSON file containing the registry configuration, as detailed in <<Configuration File Format>>.
<2> Authentication method to retrieve the file, as detailed in <<Authentication>>.

== Required Parameters

[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| configUri
| String
a| URI to file containing registry configuration. Supports `file`, `http`, `https`.

| auth
| Enum
a| Auth mechanism to access resource indicated in `configUri`.

.*Must be one of:*
* NONE: No auth needed.
* <<BASIC>>: BASIC auth.
* <<Keycloak OAuth2,KEYCLOAKOAUTH2>>: Convenience Keycloak OAuth2 implementation.
* <<OAuth2,OAUTH2>>: Generic OAuth2.

Refer to the subsections for each auth mechanism for respective configuration options.

*Default value:* NONE.

|===

== Authentication

=== BASIC

Standard BASIC auth with static credentials.

.Required Parameters
[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| username
| String
a| A username. Consider using variable substitution.

| password
| String
a| A password. Consider using variable substitution.

|===

.Example
```json
"config": {
  "configUri": "https://example.org/reg-config.json",
  "auth": "BASIC",
  "username": "MyUsername",
  "password": "${PASSWORD}" // <1>
}
```
<1> The password in this example is defined as a variable to be substituted from the config variables, system properties or environment.

=== Keycloak OAuth2

A convenience Keycloak OAuth2 implementation, allowing you to paste your chosen client configuration from the Keycloak console into the `config` section.

To retrieve it:

. Log into Keycloak (e.g. http://localhost:8080/auth).
. `Clients` -> `<Your-Client>` -> `Installation`.
. Select `Keycloak OIDC JSON` for `Format Option`.
. Copy the contents and merge into the `config` selection where indicated below.

The precise configuration you need to provide will vary depending upon your Keycloak setup.

IMPORTANT: Due to a current limitation in the underlying OAuth2 library you may be required to provide a `credentials` section to avoid issues. You can change your client type to `confidential`, or simply provide a dummy `credentials` section.

.Example
```json
"config": {
  "auth": "KeycloakOAuth2",
  "flowType": "password",
  "username": "foo",
  "password": "bar",
  // Start paste & replace your Keycloak config here.
  "realm": "apiman",
  "realm-public-key": "< snip >",
  "auth-server-url": "http://localhost:8080/auth",
  "ssl-required": "none",
  "resource": "apiman-gateway-api",
  "credentials": {
    "secret": "217b725d-7790-47a7-a3fc-5cf31f92a8db"
  }
  // End paste here.
}
```

.Required Parameters
[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| flowType
| Enum
a| The OAuth2 flow for your configuration.

.Must be one of:
* PASSWORD
* CLIENT
* AUTH_CODE
* AUTH_JWT

|===

.Optional Parameters
[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| username
| String
a| A username. Usually only useful if using the password `flowType`.

| password
| String
a| A passwor. Usually only useful if using the password `flowType`.

|===

=== OAuth2

TIP: The combination of required parameters and optional parameters will vary considerably depending upon your configuration.

.Required Parameters
[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| flowType
| Enum
a| The OAuth2 flow for your configuration.

.Must be one of:
* PASSWORD
* CLIENT
* AUTH_CODE
* AUTH_JWT

| oauthUri
| String
a| The OAuth2 URI.

| clientId
| String
a| The OAuth2 client ID.

| clientSecret
| String
a| The OAuth2 client secret.

|===

.Optional Parameters
[cols="2,1,4", options="header"]
|===

| Name
| Type
| Description

| site
| String
a| Site URI

| publicKey
| String
a| Public key

| clientSecret
| String
a| Client secret

| username
| String
a| A username. Usually only useful if using the password `flowType`.

| password
| String
a| A password. Usually only useful if using the password `flowType`.

| authorizationPath
| String
a| The authorization path

| tokenPath
| String
a| The token path

| recovationPath
| String
a| The revocation path

| scopeSeparator
| String
a| The introspection path

| logoutPath
| String
a| The logout path (OIDC)

| useBasicAuthorizationHeader
| boolean
a| Whether to use BASIC auth header (OIDC)

| clientSecretParameterName
| String
a| Client secret query parameter name (OIDC)

| userInfoPath
| String
a| User info path (OIDC)

| introspectionPath
| String
a| User info path (RFC7662)

| userAgent
| String
a| User agent

| privateKey
| String
a| Private key

|===

== Configuration File Format

Configuration of the registry is via a JSON file, https://gist.github.com/msavy/f79766b4f448672cdaf84ce4159ba2e9[the schema for which can be found on GitHub].

Broadly, it consists of:
* An `api` array containing your APIs.
* A `clients` array containing your Clients.

.Example
```json
{
    "apis": [{
        "publicAPI": true,
        "organizationId": "foo",
        "apiId": "foo",
        "version": "foo",
        "endpoint": "http://www.example.org/my-api-uri/",
        "endpointType": "rest", // <0>
        "endpointContentType": "json", // <1>
        "endpointProperties": {}, // <2>
        "parsePayload": false,
        "apiPolicies": [{
            // Plugin's JSON config.
           "policyJsonConfig": "{ \"responseCode\" : \"403\", \"ipList\" : [ \"1.2.3.4\" ] }", // <3>
           // Plugin coordinates.
           "policyImpl": "plugin:io.apiman.plugins:apiman-plugins-url-whitelist-policy:{{ book.apiman.version.release }}:war/io.apiman.gateway.engine.policies.IPWhitelistPolicy" // <3>
       }]
    }],
    "clients": [{
        "organizationId": "foo",
        "clientId": "fooClient",
        "version": "foo",
        "apiKey": "12345",
        "contracts": [{
            "apiOrgId": "foo",
            "apiId": "foo",
            "apiVersion": "foo",
            "plan": "foo",
            "policies": []
        }]
    }]
}
```
<0> See <<Endpoint Type>>.
<1> See <<Endpoint Content Type>>.
<2> See <<Endpoint Properties>>.
<3> See <<Policy Config>>.
<4> See <<Policy Implementation URI>>.

=== Endpoint Type

* `rest`: Standard RESTful endpoint type.
* `soap`: SOAP endpoint type.

=== Endpoint Content Type

The `endpointContentType` indicates which format you want apiman's responses to be in (e.g. error messages).

=== Endpoint Properties

* Authorization type:
** Basic Auth: `"authorization.type": "basic"`
** Username: `"basic-auth.username": "<username>"`
** Password: `"basic-auth.password": "<password>"`
** SSL Required?: `"basic-auth.requireSSL": "<true|false>"`
* MTLS/MSSL: `"authorization.type": "<mtls|ssl>"`. You should also provide the corresponding SSL certificate settings in the gateway's config file.

=== Policy Config



=== Policy Implementation URI
