= Gateway API

The Gateway's REST API is what the API Manager invokes when publishing APIs and Client Apps to the Gateway. Some advanced and standalone configurations may interact directly with the Gateway API.

NOTE: Some registries (such as headless) do not use the Gateway API.

{{ start }}++++
{% method %}

== Authentication

This REST API should be protected, often using BASIC authentication.

By default, the Gateway REST API requires BASIC authentication credentials, as well as a role of `apipublisher`.
In other words, the Gateway REST API can only be invoked by a valid user, and that user must have the `apipublisher` role.

The Keycloak client for this API is `apiman-gateway-api`, and the default user and password are: *apimanager*/*apiman123!*

{% sample lang="Vert.x" %}

For the Vert.x gateway, the simplest way to retrieve the necessary configuration is to generate it from your Keycloak server footnote:[Normally located at `http://localhost:8080/auth` if you're using the quickstart]:

The gateway accepts Keycloak's generated JSON, allowing you to paste your chosen client configuration from the Keycloak console into the `auth.config` section.

To retrieve it:

. Log into Keycloak (e.g. http://localhost:8080/auth).
. `Clients` -> `apiman-gateway-api` -> `Installation`.
. Select `Keycloak OIDC JSON` for `Format Option`.
. Copy the contents and merge into the `config` selection where indicated below.

The precise configuration you need to provide will vary depending upon your Keycloak setup.

IMPORTANT: Due to a current limitation in the underlying OAuth2 library you may be required to provide a `credentials` section to avoid issues. You can change your client type to `confidential`, or simply provide a dummy `credentials` section.

```json
"auth": {
  "type": "keycloak",
  "config": {
    "flowType": "PASSWORD",
    "requiredRole": "realm:apipublisher",
    // Paste and overwrite your Keycloak config here.
    "realm": "apiman",
    "realm-public-key": "<snip>",
    "auth-server-url": "http://localhost:8080/auth",
    "ssl-required": "none",
    "resource": "apiman-gateway-api",
    // A limitation in the current OAuth2 implementation means a credentials section is required
    // even if your client is not set to "confidential". Leave this dummy section if you're using non-confidential.
    "credentials": {
      "secret": "217b725d-7790-47a7-a3fc-5cf31f92a8db"
    }
    // End paste here
  }
}
```

{% sample lang="Servlet" %}

For the Servlet edition, you must modify `standalone.xml` to match your Keycloak server's settings. 

{% endmethod %}
{{ end }}++++


TIP: If you change your Keycloak settings (such as realm name, certificates, secret, etc), you should update your configuration correspondingly.
For the Vert.x version this is in the `auth` section of `conf.json` and in the Servlet edition in `standalone.xml`.
