= General Gateway Installation

If you're deploying one of the quickstarts, then it's likely that only minimal configuration is required.

IMPORTANT: Please refer to the production and deployment guides for configuring real-world deployments.
You should change apiman's keys and passwords before entering production.

== Gateway API Authentication

The Gateway's REST API is what the API Manager invokes when publishing APIs and Client Apps to the Gateway.
This REST API should be protected, often using BASIC authentication.
By default, the Gateway REST API requires BASIC authentication credentials, as well as a role of `apipublisher`.
In other words, the Gateway REST API can only be invoked by a valid user, and that user must have the `apipublisher` role.
The Keycloak client for this API is `apiman-gateway-api`, and the default user and password are: *apimanager*/*apiman123!*.


TIP: If you change your Keycloak settings (such as realm name, certificates, secret, etc), you should update your configuration correspondingly.
For the Vert.x version this is in `conf.json` and in the Serlvet edition in `standalone.xml`.
